Adding the option to specify a document-pair qulaity threshold that is only used when a website is stopped before it is fully downloaded

diff --git a/trunk/bitextor.in b/trunk/bitextor.in
--- a/trunk/bitextor.in
+++ b/trunk/bitextor.in
@@ -51,6 +51,7 @@ WEIGHTS="__PREFIX__/share/bitextor/model/keras.weights"
 SIZELIMIT=""
 TIMELIMIT=""
 DOCSIMTHRESHOLD=""
+CONDITIONALTHRESHOLD=false
 exit_program()
 {
   #echo "USAGE: $1 [-d dirname] [-l file] [-i index] [-r revindex] [-m max_lines]"
@@ -116,8 +117,12 @@ exit_program()
   echo "  -O FILE           if this option is enabled, the otput of bitextor will be redirected"
   echo "                    to file FILE, if not it is redirected to the standard output."
   echo "  -d THRESHOLD      threshold for the parallel-document confidence score. This threshold"
-  echo "                    can take real values in [0,1], being 0 equivalent to not setting any"
-  echo "                    threshold and 1 the highest threshold possible."
+  echo "                    can take real values in [0.0,1.0], being 0.0 equivalent to not setting"
+  echo "                    any threshold and 1.0 the highest threshold possible. It is possible to"
+  echo "                    set a threshold that is only used if the crawling process is stopped before"
+  echo "                    a website is completely downloaded (in this case it is easier to make errors"
+  echo "                    when aligning documents. To do so, add the character 's' at the end of the"
+  echo "                    threshold."
   echo "  -s SIZE           size limit for the crawling process; if this option is set, the crawling"
   echo "                    process will stop after the amount of data specified has been crawled."
   echo "                    This option must be an amount of Kylobytes (K), Megabytes (M) or Gigabytes (G)"
@@ -153,17 +158,30 @@ run_bitextor(){
   rm $tmpcrawl
   mkfifo $tmpcrawl
 
-  __PREFIX__/bin/bitextor-crawl $URL $SIZELIMIT $TIMELIMIT 2> $CRAWLLOG | tee $CRAWL2ETTOUT > $tmpcrawl &
+  __PREFIX__/bin/bitextor-crawl $URL $SIZELIMIT $TIMELIMIT 2> $CRAWLLOG > $tmpcrawl &
+
+  cpid=$!
   crawl_pid=$(jobs -p)
   trap "trapsigint $crawl_pid" SIGINT
   trap "trapsigint $crawl_pid" SIGUSR1
 
-  __PREFIX__/bin/bitextor-crawl2ett < $tmpcrawl 2> $CRAWL2ETTLOG | tee $ETT | \
+  tee $CRAWL2ETTOUT < $tmpcrawl | __PREFIX__/bin/bitextor-crawl2ett 2> $CRAWL2ETTLOG | tee $ETT | \
   __PREFIX__/bin/bitextor-ett2lett -l ${LANG1},$LANG2 2> $ETT2LETTLOG | tee $ETT2LETTOUT | \
-  __PREFIX__/bin/bitextor-lett2lettr 2> $LETT2LETTRLOG | tee $LETT2LETTROUT > $LETTR &
+  __PREFIX__/bin/bitextor-lett2lettr 2> $LETT2LETTRLOG | tee $LETT2LETTROUT > $LETTR 
 
-  wait
+  wait $cpid
+  CRAWLOUTPUT=$?
   rm $tmpcrawl
+
+  #if the crawl is stopped, or it reaches a limit
+  if [[ "$CRAWLOUTPUT" == "130" || "$CRAWLOUTPUT" == "4" || "$CRAWLOUTPUT" == "3" ]]; then
+      >&2 echo "Website download stopped"
+  else
+      if $CONDITIONALTHRESHOLD; then
+          DOCSIMTHRESHOLD=""
+      fi
+  fi
+
   align_segments $LETTR
 }
 
@@ -493,7 +511,13 @@ do
       ;;
     -d)
       shift
-      DOCSIMTHRESHOLD="-t $1"
+      code=$(echo $1 | sed 's/[.0-9]//g')
+      if [[ "$code" == "s" ]]; then
+          CONDITIONALTHRESHOLD=true
+          DOCSIMTHRESHOLD="-t $(echo $1 | sed 's/s//g')"
+      else
+          DOCSIMTHRESHOLD="-t $1"
+      fi
       shift
       ;;
     -h)
