Update GHA scripts and new docker GHA script

diff --git a/.github/workflows/build-and-test-bitextor-only.yaml b/.github/workflows/build-and-test-bitextor-only.yaml
--- a/.github/workflows/build-and-test-bitextor-only.yaml
+++ b/.github/workflows/build-and-test-bitextor-only.yaml
@@ -17,7 +17,7 @@ jobs:
    build_and_testing:
       name: Build and testing Bitextor only
       runs-on: ubuntu-20.04
-      timeout-minutes: 1440
+      timeout-minutes: 360
       steps:
       -  name: Install required linux packages
          run: |
@@ -91,7 +91,7 @@ jobs:
                   echo ""
                done < "${WORK}/data/fails.log"
             else
-               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               >&2 echo "ERROR: could not find the file with the detailed fails"
                exit 1
             fi
       -  name: Upload sent.gz files (artifacts)
diff --git a/.github/workflows/conda-build-test.yaml b/.github/workflows/conda-build-test.yaml
--- a/.github/workflows/conda-build-test.yaml
+++ b/.github/workflows/conda-build-test.yaml
@@ -17,7 +17,7 @@ jobs:
    conda_build_testing:
       name: Build and testing
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 360
       defaults:
          run:
             shell: bash -l {0} # Necessary for https://github.com/conda-incubator/setup-miniconda
@@ -92,7 +92,7 @@ jobs:
                   echo ""
                done < "${WORK}/data/fails.log"
             else
-               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               >&2 echo "ERROR: could not find the file with the detailed fails"
                exit 1
             fi
       -  name: Upload sent.gz files (artifacts)
diff --git a/.github/workflows/conda-intensive-tests.yaml b/.github/workflows/conda-intensive-tests.yaml
--- a/.github/workflows/conda-intensive-tests.yaml
+++ b/.github/workflows/conda-intensive-tests.yaml
@@ -43,7 +43,7 @@ jobs:
    tests:
       name: ${{ matrix.name }}
       runs-on: ubuntu-20.04
-      timeout-minutes: 1440
+      timeout-minutes: 360
       strategy:
          fail-fast: false # Continue even when a matrix job fails in order to detect as many errors as possible
          matrix:
@@ -117,7 +117,7 @@ jobs:
          id: tests
          if: ${{ env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id }}
          run: |
-            "${CONDA_PREFIX}/bitextor/tests/run-tests.sh" -t ${{ matrix.test_id }} -w "$WORK"
+            "${CONDA_PREFIX}/bitextor/tests/run-tests.sh" -t ${{ matrix.test_id }} -w "$WORK" -j 4
       -  name: Print log of tests which failed
          # https://github.com/actions/runner/issues/1173
          #if: ${{ steps.tests.conclusion != 'success' }}
@@ -146,7 +146,7 @@ jobs:
                   echo ""
                done < "${WORK}/data/fails.log"
             else
-               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               >&2 echo "ERROR: could not find the file with the detailed fails"
             fi
       -  name: Upload sent.gz files (artifacts)
          if: ${{ always() }}
