CI and tests updates and fixes (#238)
* Fix docker CI script

* Fix docker CI script

* Fix docker CI script

* Fix docker CI script

* Fix docker and conda CI scripts

* Fix docker and conda CI scripts

* Fix docker and conda CI scripts

* Fix docker CI script

* Update actions/checkout in CI scripts

* Update docker CI script

docker/build-push-action action

* Docker CI script workaround

* Add verbose info to docker CI script

* Try another version of the docker action

* Minor fix

* Try actions/checkout@v2

Actions are failing for some reason...

* Change conda build boost dependency

* Update CI scripts

* Minor fix GHA scripts

* Update submodules

* Update GHA scripts

Docker image is being built manually because the action makes some
jobs to fail intermittently:
https://github.com/actions/checkout/issues/794
https://github.com/docker/build-push-action/issues/660

* Update GHA scripts

* Minor fix conda GHA scripts

* Update GHA scripts and new docker GHA script

* Fix docker GHA script

* Fix conda build

* Refactor run-tests.sh

* Fix conda build

* Minor fix

* Fix tests

* Minor fix intensive tests

* Fix typo

* Update documentation

* Refactor bicleaner train rule

Create separate rules for bicleaner model generation based on the
flavour

* Fix bicleaner AI tests

Adding metadata.yaml is not longer necessary

* Fix bicleaner rule

* Minor fix

* Fix dryrun from intensive tests

* Fix conda installation in GHA

* Fix conda installation in GHA scripts

* Fix bicleaner model generation

Dictionary train prefix was not being correctly handled

Co-authored-by: Leopoldo Pla <leopoldoplasempere@gmail.com>
Co-authored-by: Leopoldo Pla <lpla@dlsi.ua.es>

diff --git a/.github/workflows/build-and-test-bitextor-only.yaml b/.github/workflows/build-and-test-bitextor-only.yaml
--- a/.github/workflows/build-and-test-bitextor-only.yaml
+++ b/.github/workflows/build-and-test-bitextor-only.yaml
@@ -5,12 +5,10 @@ on:
       paths-ignore:
          - '**.md'
          - 'docs/**'
-         - 'img/**'
    pull_request:
       paths-ignore:
          - '**.md'
          - 'docs/**'
-         - 'img/**'
 
 env:
    WORK: ${{ github.workspace }}
@@ -19,7 +17,7 @@ jobs:
    build_and_testing:
       name: Build and testing Bitextor only
       runs-on: ubuntu-20.04
-      timeout-minutes: 1440
+      timeout-minutes: 360
       steps:
       -  name: Install required linux packages
          run: |
@@ -57,7 +55,7 @@ jobs:
       -  name: Compiling bitextor and submodules
          run: |
             mkdir build_cmake && cd build_cmake
-            cmake -DSKIP_MGIZA=ON -DCMAKE_INSTALL_PREFIX=/usr ..
+            cmake -DCMAKE_INSTALL_PREFIX=/usr ..
             make -j
             sudo make install
       -  name: Run tests
@@ -93,7 +91,7 @@ jobs:
                   echo ""
                done < "${WORK}/data/fails.log"
             else
-               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               >&2 echo "ERROR: could not find the file with the detailed fails"
                exit 1
             fi
       -  name: Upload sent.gz files (artifacts)
diff --git a/.github/workflows/conda-build-test.yaml b/.github/workflows/conda-build-test.yaml
--- a/.github/workflows/conda-build-test.yaml
+++ b/.github/workflows/conda-build-test.yaml
@@ -2,12 +2,13 @@ name: Build and test conda environment
 
 on:
    push:
-      branches:
-         - master
       paths-ignore:
          - '**.md'
          - 'docs/**'
-         - 'img/**'
+   pull_request:
+      paths-ignore:
+         - '**.md'
+         - 'docs/**'
 
 env:
    WORK: ${{ github.workspace }}
@@ -16,7 +17,7 @@ jobs:
    conda_build_testing:
       name: Build and testing
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 360
       defaults:
          run:
             shell: bash -l {0} # Necessary for https://github.com/conda-incubator/setup-miniconda
@@ -39,10 +40,23 @@ jobs:
          run: |
             # Tmp workaround: we install the package in the same environment (waiting answers: https://github.com/conda-incubator/setup-miniconda/issues/221)
 
-            bitextor_package=$(ls "$CONDA_PREFIX/../../envs/bitextor-pkg-build/conda-bld/linux-64" | grep ^bitextor.*[.]tar[.]bz2$ | sort -r | head -n 1)
+            bitextor_pkg_prefix="$CONDA_PREFIX/../../envs/bitextor-pkg-build/conda-bld/linux-64"
+            bitextor_pkg=$(ls "$bitextor_pkg_prefix" | grep ^bitextor.*[.]tar[.]bz2$ | sort -r | head -n 1)
 
-            conda install -y "$CONDA_PREFIX/../../envs/bitextor-pkg-build/conda-bld/linux-64/$bitextor_package"
-            conda update -y --all
+            if [[ -z "$bitextor_pkg" ]]; then
+               >&2 echo "ERROR: could not find the package"
+
+               if [[ ! -d "$bitextor_pkg_prefix" ]]; then
+                  >&2 echo "ERROR: dir '$bitextor_pkg_prefix' does not exist"
+               else
+                  ls "$bitextor_pkg_prefix"
+               fi
+
+               exit 1
+            fi
+
+            conda install --offline -y "${bitextor_pkg_prefix}/$bitextor_pkg"
+            conda update -y --only-deps bitextor # Necessary in order to install dependencies from local builds
             command -v "bitextor" || \
                (>&2 echo "Binary 'bitextor' not available"; exit 1)
       -  name: Run tests
@@ -78,7 +92,7 @@ jobs:
                   echo ""
                done < "${WORK}/data/fails.log"
             else
-               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               >&2 echo "ERROR: could not find the file with the detailed fails"
                exit 1
             fi
       -  name: Upload sent.gz files (artifacts)
diff --git a/.github/workflows/conda-intensive-tests.yaml b/.github/workflows/conda-intensive-tests.yaml
--- a/.github/workflows/conda-intensive-tests.yaml
+++ b/.github/workflows/conda-intensive-tests.yaml
@@ -6,24 +6,12 @@ on:
    workflow_dispatch:
       inputs:
          conda_package:
-            description: 'Package which will be installed'
+            description: 'Package from repo. Syntax: pkg[==version[=build]]'
             required: false
             default: 'bitextor'
-            type: choice
-            options:
-               - 'bitextor'
-               - 'bitextor-nightly'
-         conda_version:
-            description: 'Version which will be looked for'
-            required: false
-            default: ''
-         conda_build:
-            description: 'Build which will be looked for'
-            required: false
-            default: ''
          create_build:
             type: boolean
-            description: 'Create build instead of downloading last package available'
+            description: 'Create build (i.e. do not pull pkg from repo)'
             default: true
          build_ref:
             description: 'Ref to use for local build (i.e. branch, tag or commit)'
@@ -55,7 +43,7 @@ jobs:
    tests:
       name: ${{ matrix.name }}
       runs-on: ubuntu-20.04
-      timeout-minutes: 1440
+      timeout-minutes: 360
       strategy:
          fail-fast: false # Continue even when a matrix job fails in order to detect as many errors as possible
          matrix:
@@ -88,45 +76,48 @@ jobs:
             activate-environment: bitextor-tests
             channels: conda-forge,bitextor,bioconda,dmnapolitano,esarrias
       -  uses: actions/checkout@v3
-         if: ${{ env.CREATE_BUILD }}
+         if: ${{ env.CREATE_BUILD == 'true' }}
          with:
             submodules: 'recursive'
             ref: ${{ env.BUILD_REF }}
       -  name: Create Bitextor conda build
-         if: ${{ env.CREATE_BUILD && (env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id) }}
+         if: ${{ env.CREATE_BUILD == 'true' && (env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id) }}
          working-directory: ./conda-build
          run: |
             ./make_build.sh -n bitextor-pkg -e bitextor-pkg-build -p 3.8 -s -r
       -  name: Install Bitextor locally
-         if: ${{ env.CREATE_BUILD && (env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id) }}
+         if: ${{ env.CREATE_BUILD == 'true' && (env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id) }}
          run: |
             # Tmp workaround: we install the package in the same environment (waiting answers: https://github.com/conda-incubator/setup-miniconda/issues/221)
 
-            bitextor_package=$(ls "$CONDA_PREFIX/../../envs/bitextor-pkg-build/conda-bld/linux-64" | grep ^bitextor.*[.]tar[.]bz2$ | sort -r | head -n 1)
+            bitextor_pkg_prefix="$CONDA_PREFIX/../../envs/bitextor-pkg-build/conda-bld/linux-64"
+            bitextor_pkg=$(ls "$bitextor_pkg_prefix" | grep ^bitextor.*[.]tar[.]bz2$ | sort -r | head -n 1)
 
-            conda install -y "$CONDA_PREFIX/../../envs/bitextor-pkg-build/conda-bld/linux-64/$bitextor_package"
-            conda update -y --all
+            if [[ -z "$bitextor_pkg" ]]; then
+               >&2 echo "ERROR: could not find the package"
+
+               if [[ ! -d "$bitextor_pkg_prefix" ]]; then
+                  >&2 echo "ERROR: dir '$bitextor_pkg_prefix' does not exist"
+               else
+                  ls "$bitextor_pkg_prefix"
+               fi
+
+               exit 1
+            fi
+
+            conda install --offline -y "${bitextor_pkg_prefix}/$bitextor_pkg"
+            conda update -y --only-deps bitextor # Necessary in order to install dependencies from local builds
             command -v "bitextor" || \
                (>&2 echo "Binary 'bitextor' not available"; exit 1)
       -  name: Install Bitextor from repo
-         if: ${{ !env.CREATE_BUILD && (env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id) }}
+         if: ${{ env.CREATE_BUILD == 'false' && (env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id) }}
          run: |
-            v="${{ env.CONDA_PACKAGE }}"
-
-            if [[ "${{ github.event.inputs.conda_version }}" != "" ]]; then
-               v="${v}=${{ github.event.inputs.conda_version }}"
-
-               if [[ "${{ github.event.inputs.conda_build }}" != "" ]]; then
-                  v="${v}=${{ github.event.inputs.conda_build }}"
-               fi
-            fi
-
-            conda install -y "$v"
+            conda install -y "${{ env.CONDA_PACKAGE }}"
       -  name: Run tests
          id: tests
          if: ${{ env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id }}
          run: |
-            "${CONDA_PREFIX}/bitextor/tests/run-tests.sh" -t ${{ matrix.test_id }} -w "$WORK"
+            "${CONDA_PREFIX}/bitextor/tests/run-tests.sh" -t ${{ matrix.test_id }} -w "$WORK" -j 4
       -  name: Print log of tests which failed
          # https://github.com/actions/runner/issues/1173
          #if: ${{ steps.tests.conclusion != 'success' }}
@@ -155,7 +146,7 @@ jobs:
                   echo ""
                done < "${WORK}/data/fails.log"
             else
-               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               >&2 echo "ERROR: could not find the file with the detailed fails"
             fi
       -  name: Upload sent.gz files (artifacts)
          if: ${{ always() }}
