Action scripts timeout increased

diff --git a/.github/workflows/buildCondaInstallAndTest.yaml b/.github/workflows/buildCondaInstallAndTest.yaml
--- a/.github/workflows/buildCondaInstallAndTest.yaml
+++ b/.github/workflows/buildCondaInstallAndTest.yaml
@@ -4,6 +4,7 @@ jobs:
    conda_build_and_testing:
       name: Build with conda and testing
       runs-on: ubuntu-latest
+      timeout-minutes: 1440
       steps:
       -  name: Set distrib release version if not set
          env:
@@ -46,10 +47,13 @@ jobs:
          run: |
             . ~/miniconda3/etc/profile.d/conda.sh
             conda activate bitextor-installation
-            if [[ -f "$CONDA_PREFIX/bitextor/run-tests-mt.sh" ]]; then
+            if [[ -f "$CONDA_PREFIX/bitextor/run-tests.sh" ]]; then
+                chmod 775 $CONDA_PREFIX/bitextor/run-tests.sh
+                $CONDA_PREFIX/bitextor/run-tests.sh -w "$BITEXTOR" -j 4
+            elif [[ -f "$CONDA_PREFIX/bitextor/run-tests-mt.sh" ]]; then
                 chmod 775 $CONDA_PREFIX/bitextor/run-tests-mt.sh
                 $CONDA_PREFIX/bitextor/run-tests-mt.sh -w "$BITEXTOR" -j 4
             else
-                chmod 775 $CONDA_PREFIX/bitextor/run-tests.sh
-                $CONDA_PREFIX/bitextor/run-tests.sh -w "$BITEXTOR" -j 4
+                echo "(error) No test script found."
+                exit 1
             fi
