Actions and tests updated

diff --git a/.github/workflows/condaIntensiveTests.yaml b/.github/workflows/condaIntensiveTests.yaml
--- a/.github/workflows/condaIntensiveTests.yaml
+++ b/.github/workflows/condaIntensiveTests.yaml
@@ -1,5 +1,7 @@
 name: Intensive tests with conda
 on:
+   schedule:
+      - cron: '0 3 * * 0'
    workflow_dispatch:
       inputs:
          conda_version:
@@ -14,7 +16,7 @@ jobs:
    tests_mt:
       name: Tests MT
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -40,10 +42,39 @@ jobs:
 
             conda install -y -c bitextor "bitextor${v}"
             "${CONDA_PREFIX}/bitextor/run-tests.sh" -t 0x01
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/data/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/data/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
    tests_db:
       name: Tests dictionary based
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -69,10 +100,39 @@ jobs:
 
             conda install -y -c bitextor "bitextor${v}"
             "${CONDA_PREFIX}/bitextor/run-tests.sh" -t 0x02
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/data/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/data/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
    tests_gendic:
       name: Tests generate dictionary
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -98,10 +158,39 @@ jobs:
 
             conda install -y -c bitextor "bitextor${v}"
             "${CONDA_PREFIX}/bitextor/run-tests.sh" -t 0x04
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/data/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/data/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
    tests_genbicleaner:
       name: Tests generate bicleaner model
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -127,10 +216,39 @@ jobs:
 
             conda install -y -c bitextor "bitextor${v}"
             "${CONDA_PREFIX}/bitextor/run-tests.sh" -t 0x08
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/data/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/data/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
    tests_gendic_genbicleaner:
       name: Tests generate dictionary and bicleaner model
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -156,10 +274,39 @@ jobs:
 
             conda install -y -c bitextor "bitextor${v}"
             "${CONDA_PREFIX}/bitextor/run-tests.sh" -t 0x10
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/data/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/data/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
    tests_mt_db:
       name: Tests combining dictionaries and MT
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -185,10 +332,39 @@ jobs:
 
             conda install -y -c bitextor "bitextor${v}"
             "${CONDA_PREFIX}/bitextor/run-tests.sh" -t 0x20
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/data/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/data/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
    tests_others:
       name: Other tests
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -214,3 +390,32 @@ jobs:
 
             conda install -y -c bitextor "bitextor${v}"
             "${CONDA_PREFIX}/bitextor/run-tests.sh" -t 0x40
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/data/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/data/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
diff --git a/.github/workflows/dockerIntensiveTests.yaml b/.github/workflows/dockerIntensiveTests.yaml
--- a/.github/workflows/dockerIntensiveTests.yaml
+++ b/.github/workflows/dockerIntensiveTests.yaml
@@ -1,5 +1,7 @@
 name: Intensive tests with docker
 on:
+   schedule:
+      - cron: '0 3 * * 0'
    workflow_dispatch:
       inputs:
          docker_tag:
@@ -10,7 +12,10 @@ jobs:
    tests_mt:
       name: Tests MT
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
+      env:
+            WORK: ${{ github.workspace }}
+            WORK_DOCKER: '/home/docker'
       steps:
       -  name: Run
          run: |
@@ -33,12 +38,45 @@ jobs:
             sudo docker run --rm hello-world > /dev/null
 
             # Run tests with docker
+            mkdir "${WORK}/docker-volume"
             sudo docker pull "bitextor/bitextor${tag}"
-            sudo docker run --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" -c 'bitextor/run-tests.sh -t 0x01'
+            sudo docker run -v "${WORK}/docker-volume:${WORK_DOCKER}/volume" --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" \
+                  -c 'bitextor/run-tests.sh -t 0x01; \
+                      cp -f "${WORK_DOCKER}/data/fails.log" "${WORK_DOCKER}/volume" 2> /dev/null && \
+                      cp -f -r "${WORK_DOCKER}/reports" "${WORK_DOCKER}/volume"'
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/docker-volume/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/docker-volume/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/docker-volume/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/docker-volume/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
    tests_db:
       name: Tests dictionary based
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -61,12 +99,45 @@ jobs:
             sudo docker run --rm hello-world > /dev/null
 
             # Run tests with docker
+            mkdir "${WORK}/docker-volume"
             sudo docker pull "bitextor/bitextor${tag}"
-            sudo docker run --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" -c 'bitextor/run-tests.sh -t 0x02'
+            sudo docker run -v "${WORK}/docker-volume:${WORK_DOCKER}/volume" --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" \
+                  -c 'bitextor/run-tests.sh -t 0x02; \
+                      cp -f "${WORK_DOCKER}/data/fails.log" "${WORK_DOCKER}/volume" 2> /dev/null && \
+                      cp -f -r "${WORK_DOCKER}/reports" "${WORK_DOCKER}/volume"'
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/docker-volume/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/docker-volume/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/docker-volume/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/docker-volume/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
    tests_gendic:
       name: Tests generate dictionary
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -89,12 +160,45 @@ jobs:
             sudo docker run --rm hello-world > /dev/null
 
             # Run tests with docker
+            mkdir "${WORK}/docker-volume"
             sudo docker pull "bitextor/bitextor${tag}"
-            sudo docker run --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" -c 'bitextor/run-tests.sh -t 0x04'
+            sudo docker run -v "${WORK}/docker-volume:${WORK_DOCKER}/volume" --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" \
+                  -c 'bitextor/run-tests.sh -t 0x04; \
+                      cp -f "${WORK_DOCKER}/data/fails.log" "${WORK_DOCKER}/volume" 2> /dev/null && \
+                      cp -f -r "${WORK_DOCKER}/reports" "${WORK_DOCKER}/volume"'
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/docker-volume/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/docker-volume/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/docker-volume/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/docker-volume/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
    tests_genbicleaner:
       name: Tests generate bicleaner model
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -117,12 +221,45 @@ jobs:
             sudo docker run --rm hello-world > /dev/null
 
             # Run tests with docker
+            mkdir "${WORK}/docker-volume"
             sudo docker pull "bitextor/bitextor${tag}"
-            sudo docker run --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" -c 'bitextor/run-tests.sh -t 0x08'
+            sudo docker run -v "${WORK}/docker-volume:${WORK_DOCKER}/volume" --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" \
+                  -c 'bitextor/run-tests.sh -t 0x08; \
+                      cp -f "${WORK_DOCKER}/data/fails.log" "${WORK_DOCKER}/volume" 2> /dev/null && \
+                      cp -f -r "${WORK_DOCKER}/reports" "${WORK_DOCKER}/volume"'
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/docker-volume/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/docker-volume/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/docker-volume/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/docker-volume/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
    tests_gendic_genbicleaner:
       name: Tests generate dictionary and bicleaner model
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -145,12 +282,45 @@ jobs:
             sudo docker run --rm hello-world > /dev/null
 
             # Run tests with docker
+            mkdir "${WORK}/docker-volume"
             sudo docker pull "bitextor/bitextor${tag}"
-            sudo docker run --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" -c 'bitextor/run-tests.sh -t 0x10'
+            sudo docker run -v "${WORK}/docker-volume:${WORK_DOCKER}/volume" --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" \
+                  -c 'bitextor/run-tests.sh -t 0x10; \
+                      cp -f "${WORK_DOCKER}/data/fails.log" "${WORK_DOCKER}/volume" 2> /dev/null && \
+                      cp -f -r "${WORK_DOCKER}/reports" "${WORK_DOCKER}/volume"'
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/docker-volume/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/docker-volume/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/docker-volume/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/docker-volume/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
    tests_mt_db:
       name: Tests combining dictionaries and MT
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -173,12 +343,45 @@ jobs:
             sudo docker run --rm hello-world > /dev/null
 
             # Run tests with docker
+            mkdir "${WORK}/docker-volume"
             sudo docker pull "bitextor/bitextor${tag}"
-            sudo docker run --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" -c 'bitextor/run-tests.sh -t 0x20'
+            sudo docker run -v "${WORK}/docker-volume:${WORK_DOCKER}/volume" --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" \
+                  -c 'bitextor/run-tests.sh -t 0x20; \
+                      cp -f "${WORK_DOCKER}/data/fails.log" "${WORK_DOCKER}/volume" 2> /dev/null && \
+                      cp -f -r "${WORK_DOCKER}/reports" "${WORK_DOCKER}/volume"'
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/docker-volume/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/docker-volume/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/docker-volume/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/docker-volume/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
    tests_others:
       name: Other tests
       runs-on: ubuntu-20.04
-      timeout-minutes: 300
+      timeout-minutes: 600
       steps:
       -  name: Run
          run: |
@@ -201,5 +404,38 @@ jobs:
             sudo docker run --rm hello-world > /dev/null
 
             # Run tests with docker
+            mkdir "${WORK}/docker-volume"
             sudo docker pull "bitextor/bitextor${tag}"
-            sudo docker run --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" -c 'bitextor/run-tests.sh -t 0x40'
+            sudo docker run -v "${WORK}/docker-volume:${WORK_DOCKER}/volume" --name bitextor --entrypoint /bin/bash --rm "bitextor/bitextor${tag}" \
+                  -c 'bitextor/run-tests.sh -t 0x40; \
+                      cp -f "${WORK_DOCKER}/data/fails.log" "${WORK_DOCKER}/volume" 2> /dev/null && \
+                      cp -f -r "${WORK_DOCKER}/reports" "${WORK_DOCKER}/volume"'
+      -  name: Print log of tests which failed
+         if: ${{ always() }}
+         env:
+            WORK: ${{ github.workspace }}
+         run: |
+            if [[ -f "${WORK}/docker-volume/fails.log" ]]; then
+               while read line; do
+                  eval "array=($line)"
+                  status=${array[0]}
+                  notest=${array[1]}
+                  exit_code=${array[2]}
+
+                  str="# Test $notest (exit code / desc.: $exit_code) #"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+                  echo "$str"
+                  eval $(echo printf '"#%0.s"' {1..${#str}}) && printf "\n"
+
+                  if [[ "$(ls ${WORK}/docker-volume/reports/ | grep ${notest}- || true)" != "" ]]; then
+                     report_file="$(ls ${WORK}/docker-volume/reports/${notest}-* | head -n 1)"
+                     awk -v prefix="(log test $notest)" '{print prefix" "$0}' "$report_file"
+                  else
+                     echo "(warning) No report file found for test $notest (this might be normal depending on the test; check the description)"
+                  fi
+                  echo ""
+               done < "${WORK}/docker-volume/fails.log"
+            else
+               >&2 echo "ERROR: could not find the file which contain the fails, and should exist"
+               exit 1
+            fi
