Update GHA scripts

diff --git a/.github/workflows/conda-build-test.yaml b/.github/workflows/conda-build-test.yaml
--- a/.github/workflows/conda-build-test.yaml
+++ b/.github/workflows/conda-build-test.yaml
@@ -5,12 +5,10 @@ on:
       paths-ignore:
          - '**.md'
          - 'docs/**'
-         - 'img/**'
    pull_request:
       paths-ignore:
          - '**.md'
          - 'docs/**'
-         - 'img/**'
 
 env:
    WORK: ${{ github.workspace }}
@@ -42,10 +40,22 @@ jobs:
          run: |
             # Tmp workaround: we install the package in the same environment (waiting answers: https://github.com/conda-incubator/setup-miniconda/issues/221)
 
-            bitextor_package=$(ls "$CONDA_PREFIX/../../envs/bitextor-pkg-build/conda-bld/linux-64" | grep ^bitextor.*[.]tar[.]bz2$ | sort -r | head -n 1)
+            bitextor_pkg_prefix="$CONDA_PREFIX/../../envs/bitextor-pkg-build/conda-bld/linux-64"
+            bitextor_pkg=$(ls "$bitextor_pkg_prefix" | grep ^bitextor.*[.]tar[.]bz2$ | sort -r | head -n 1)
 
-            conda install -y "$CONDA_PREFIX/../../envs/bitextor-pkg-build/conda-bld/linux-64/$bitextor_package"
-            conda update -y --all
+            if [[ -z "$bitextor_pkg" ]]; then
+               >&2 echo "ERROR: could not find the package"
+
+               if [[ ! -d "$bitextor_pkg_prefix" ]]; then
+                  >&2 echo "ERROR: dir '$bitextor_pkg_prefix' does not exist"
+               else
+                  ls "$bitextor_pkg_prefix"
+               fi
+
+               exit 1
+            fi
+
+            conda install -y "${bitextor_pkg_prefix}/$bitextor_pkg"
             command -v "bitextor" || \
                (>&2 echo "Binary 'bitextor' not available"; exit 1)
       -  name: Run tests
diff --git a/.github/workflows/conda-intensive-tests.yaml b/.github/workflows/conda-intensive-tests.yaml
--- a/.github/workflows/conda-intensive-tests.yaml
+++ b/.github/workflows/conda-intensive-tests.yaml
@@ -6,24 +6,12 @@ on:
    workflow_dispatch:
       inputs:
          conda_package:
-            description: 'Package which will be installed'
+            description: 'Package from repo. Syntax: pkg[==version[=build]]'
             required: false
             default: 'bitextor'
-            type: choice
-            options:
-               - 'bitextor'
-               - 'bitextor-nightly'
-         conda_version:
-            description: 'Version which will be looked for'
-            required: false
-            default: ''
-         conda_build:
-            description: 'Build which will be looked for'
-            required: false
-            default: ''
          create_build:
             type: boolean
-            description: 'Create build instead of downloading last package available'
+            description: 'Create build (i.e. do not pull pkg from repo)'
             default: true
          build_ref:
             description: 'Ref to use for local build (i.e. branch, tag or commit)'
@@ -102,26 +90,28 @@ jobs:
          run: |
             # Tmp workaround: we install the package in the same environment (waiting answers: https://github.com/conda-incubator/setup-miniconda/issues/221)
 
-            bitextor_package=$(ls "$CONDA_PREFIX/../../envs/bitextor-pkg-build/conda-bld/linux-64" | grep ^bitextor.*[.]tar[.]bz2$ | sort -r | head -n 1)
+            bitextor_pkg_prefix="$CONDA_PREFIX/../../envs/bitextor-pkg-build/conda-bld/linux-64"
+            bitextor_pkg=$(ls "$bitextor_pkg_prefix" | grep ^bitextor.*[.]tar[.]bz2$ | sort -r | head -n 1)
 
-            conda install -y "$CONDA_PREFIX/../../envs/bitextor-pkg-build/conda-bld/linux-64/$bitextor_package"
-            conda update -y --all
+            if [[ -z "$bitextor_pkg" ]]; then
+               >&2 echo "ERROR: could not find the package"
+
+               if [[ ! -d "$bitextor_pkg_prefix" ]]; then
+                  >&2 echo "ERROR: dir '$bitextor_pkg_prefix' does not exist"
+               else
+                  ls "$bitextor_pkg_prefix"
+               fi
+
+               exit 1
+            fi
+
+            conda install -y "${bitextor_pkg_prefix}/$bitextor_pkg"
             command -v "bitextor" || \
                (>&2 echo "Binary 'bitextor' not available"; exit 1)
       -  name: Install Bitextor from repo
          if: ${{ env.CREATE_BUILD == 'false' && (env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id) }}
          run: |
-            v="${{ env.CONDA_PACKAGE }}"
-
-            if [[ "${{ github.event.inputs.conda_version }}" != "" ]]; then
-               v="${v}=${{ github.event.inputs.conda_version }}"
-
-               if [[ "${{ github.event.inputs.conda_build }}" != "" ]]; then
-                  v="${v}=${{ github.event.inputs.conda_build }}"
-               fi
-            fi
-
-            conda install -y "$v"
+            conda install -y "${{ env.CONDA_PACKAGE }}"
       -  name: Run tests
          id: tests
          if: ${{ env.TEST_ID == 'all' || env.TEST_ID == matrix.test_id }}
