Actions updated

diff --git a/.github/workflows/condaBuildTestUpload.yaml b/.github/workflows/condaBuildTestUpload.yaml
--- a/.github/workflows/condaBuildTestUpload.yaml
+++ b/.github/workflows/condaBuildTestUpload.yaml
@@ -55,19 +55,19 @@ jobs:
       -  name: Run tests
          id: tests
          env:
-            BITEXTOR: ${{ github.workspace }}
+            WORK: ${{ github.workspace }}
          run: |
             . ~/miniconda3/etc/profile.d/conda.sh
             conda activate bitextor-installation
             if [[ -f "$CONDA_PREFIX/bitextor/run-tests-min.sh" ]]; then
-                chmod 775 "$CONDA_PREFIX/bitextor/run-tests-min.sh"
-                "$CONDA_PREFIX/bitextor/run-tests-min.sh" -w "$BITEXTOR" -j 4
+               chmod 775 "$CONDA_PREFIX/bitextor/run-tests-min.sh"
+               "$CONDA_PREFIX/bitextor/run-tests-min.sh" -w "$WORK" -j 4
             elif [[ -f "$CONDA_PREFIX/bitextor/run-tests.sh" ]]; then
-                chmod 775 "$CONDA_PREFIX/bitextor/run-tests.sh"
-                "$CONDA_PREFIX/bitextor/run-tests.sh" -w "$BITEXTOR" -j 4
+               chmod 775 "$CONDA_PREFIX/bitextor/run-tests.sh"
+               "$CONDA_PREFIX/bitextor/run-tests.sh" -w "$WORK" -j 4
             else
-                echo "(error) No test script found."
-                exit 1
+               echo "(error) No test script found."
+               exit 1
             fi
       -  name: Print log of tests which failed
          if: ${{ always() }}
